colordiff -u .aliases ~/.aliases
colordiff -u .base16-tmux ~/.base16-tmux
colordiff -u .bashrc ~/.bashrc
colordiff -u config.h ~/Projects/dwm/config.h
colordiff -u .profile ~/.profile
colordiff -u .tmux.conf ~/.tmux.conf
colordiff -u .tvbindings ~/.tvbindings
colordiff -u .vimrc ~/.vimrc
colordiff -u .xinitrc ~/.xinitrc
colordiff -u .Xresources ~/.Xresources
colordiff -u .zshrc ~/.zshrc
