#!/bin/sh
# If no url given. Opens browser. For using script as $BROWSER.
[ -z "$1" ] && { "$BROWSER"; exit; }

# debug line
# echo "$1" >> /home/sumofalln00bs/Links.txt
case "$1" in
	*mkv|*webm|*mp4|*gif|*youtube.com*|*hooktube.com*)
		setsid openvideo "$1" >/dev/null 2>&1 & ;;
	*png|*jpg|*jpe|*jpeg)
		setsid feh "$1" >/dev/null 2>&1 & ;;
	*mp3|*flac|*opus|*mp3?source)
		setsid tsp wget "$1" >/dev/null 2>&1 & ;;
    *magnet:*)
        setsid transmission-remote -a "$1" >/dev/null 2>&1 && note "Torrent Added..." >/dev/null 2>&1 & ;;
	*) setsid "$BROWSER" "$1" >/dev/null 2>&1 & ;;
esac
